### ISSUE TITLE
Need a better way to enforce sequence of code update steps

### ISSUE THREAD

**Issue by anoo1** [openbmc/phosphor-bmc-code-mgmt#6]
Some code update functions use systemd service files to execute scripts and perform Delete and Write operations. But these systemd service files aren't been monitored for completion so race conditions can occur. As a workaround, sleep() have been added to some of the functions.

Opening this issue to explore better options than arbitrary sleep calls, since they still not guaranteed that the service has finished, it's just a value based on observation.

Some ideas in no particular order:
- Use targets that contain all needed services and monitor the single target status.
- Codify the script logic in c++.
- Have a function that monitors systemd service files (reference an earlier attempt with https://github.com/openbmc/openbmc/issues/2857)

**Comment by leiyu-bytedance** [comment]
Is it possible to add some Wants/Before/After configs in the unit files to solve the issue?
The good part is that the C++ code does not have to call the system units one-by-one anymore, instead, it calls one systemd unit, and the unit will start other systemd units by sequence.

**Comment by bradbishop** [comment]
> The good part is that the C++ code does not have to call the system units one-by-one

If we have scripts calling other scripts I wonder if that could be simplified or reduced down to a single script?

Are there any other benefits besides the one above to using systemd over a more conventional implementation for launching scripts/programs, such as this one:
https://github.com/openbmc/jsnbd/blob/master/nbd-proxy.c#L379

**Comment by anoo1** [comment]
> Is it possible to add some Wants/Before/After configs in the unit files to solve the issue?

Partially. The remaining issue is that we want the function to return until the script (run by a service file) is complete. For example a Delete or Set Priority call would not return to the caller until the operations finished.

> Are there any other benefits besides the one above to using system over a more conventional implementation for launching scripts/programs

Hadn't thought of that. That could be an option, instead of executing the script via a service file.

**Comment by anoo1** [comment]
Adding function for running commands in child process:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/39844

**Comment by anoo1** [comment]
Closing. First function (factory reset) migrated to exec instead of using systemd service files.
