### ISSUE TITLE
Test case SignatureTest.TestSignatureVerify() fails when `verify-full-signature` is enabled

### ISSUE THREAD

**Issue by leiyu-bytedance** [openbmc/phosphor-bmc-code-mgmt#9]
The unit test case SignatureTest.TestSignatureVerify() passes with default config.
But when `verify-full-signature` is enabled, the test case fails.

It looks like the test case needs to be updated to support both cases.

**Comment by lxwinspur** [comment]
Thanks.

resolved: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/46256
